version: 0.2
env:
  variables:
    APP_NAME: "training-ddd-and-design-patterns-java"
    CONTAINER_NAME: "andersoncontreira/training-ddd-and-design-patterns-java"
phases:
  pre_build:
    commands:
      # AWS ECR Login
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      # Install project dependencies locally

      # Build Docker image
      - |
        docker build \
          --build-arg PROJECT_NAME=$APP_NAME \
          --build-arg ENVIRONMENT_NAME=$ENVIRONMENT_NAME \
          --build-arg JAR_FILE=build/libs/\*.jar \
          -t $CONTAINER_NAME \
          -f docker/java/Dockerfile .
  post_build:
    commands:
#      - echo Installing test requirements
#      - pip install -r ./requirements-tests.txt
#      - echo Running unit testes
#      - ./bin/tests/unit-coverage-no-report-html.sh
#      # Uninstall test dependencies
#      - pip uninstall -r requirements-tests.txt -y
    finally:
      # Tag Docker images
      - docker tag $CONTAINER_NAME:latest $REPOSITORY_URI:latest
      # Push Docker images
      - docker push $REPOSITORY_URI:latest
      # Write imagedefinitions.json
      - printf '[' > imagedefinitions.json
      - printf '{"name":"%s","imageUri":"%s"}' $CONTAINER_NAME $REPOSITORY_URI:latest >> imagedefinitions.json
      - printf ']' >> imagedefinitions.json
reports:
  UnitTestsReports:
    files:
      - 'target/unit/clover.xml'
    file-format: 'CLOVERXML'
artifacts:
  files: imagedefinitions.json